### ISSUE TITLE
Entrypoint issues when using custom DEDICATED_CFG

### ISSUE THREAD

**Issue by KemTM** [EvoEsports/docker-trackmania#32]
Based on what I see on the `entrypoint.sh` file there are a couple of problems that I encountered when using my own supplied config and setting `DEDICATED_CFG` env.

1. Despite the dedicated server authorization infos (masterserver login+password) entered in my config file, the entrypoint still demands that `MASTER_LOGIN` and `MASTER_PASSWORD` envs are set. This can be worked around by supplying dummy values.
2. Despite using a different config file, the entrypoint still writes the defaults (and the aforementioned masterserver account dummies) to `dedicated_cfg.txt`, which is not necessary and can even be harmful if `UserData` volume is shared across multiple containers.

**Comment by ItsPhenom** [comment]
Fixed with https://github.com/EvoEsports/docker-trackmania/commit/13196a7ddba8dca5e6e35c31dfda87a4e05e178c
