### ISSUE TITLE
add more configuration options, like disable horns

### ISSUE THREAD

**Issue by reaby** [EvoEsports/docker-trackmania#33]

**Comment by reaby** [comment]
Also would be nice to disable p2p for download and upload

**Comment by Chris92de** [comment]
> Also would be nice to disable p2p for download and upload
P2P is not used in TM2020 servers anymore.

**Comment by GreepTheSheep** [comment]
Would be nice to add an Environment variable for setting the password of the SuperAdmin for XML-RPC connection

**Comment by ItsPhenom** [comment]
> Would be nice to add an Environment variable for setting the password of the SuperAdmin for XML-RPC connection 

Can do!

**Comment by ItsPhenom** [comment]
Although it took me almost a year to push the changes.. done with https://github.com/EvoEsports/docker-trackmania/commit/13196a7ddba8dca5e6e35c31dfda87a4e05e178c 👍
