### ISSUE TITLE
Server access trough IP link

### ISSUE THREAD

**Issue by ibaraki-douji** [EvoEsports/docker-trackmania#42]
Hi,

I'm trying to join my server with IP / Port and yes i do have club access but it does not work.

I tried to join from the club it work, from the link ID it works but not the IP/Port. (so should not be a port forward issue)

I tested IP/Port with and without master password without any success.

The only way i got access with IP/Port was in a local network but i don't want that ... (also in local network free account can join with IP)

Is it just cuz IP is local only ? If yes, Is there a way to bypass it ?
Or am i missing something ??

**Comment by Chris92de** [comment]
You'd have to use your external IP to join, not the local network IP.
However, is there any specific reason you wanna join via IP:Port instead of the club or join link?
